#################################################################
# Config for Agent Factory
#################################################################

#################################################################
# Factory Discovery Url
#################################################################
factory_discovery_url="http://127.0.0.1:4000"

#################################################################
# Facvtory Evaluation Service
#################################################################
factory_evaluation_service_url="http://127.0.0.1:7000"

#################################################################
# Facvtory Memory Service
#################################################################
factory_memory_service_url="http://127.0.0.1:5000"
